spring.application.name=contatos-api

spring.datasource.url=jdbc:sqlite:${SQLITE_PATH}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8081